# Generated by Django 4.2.7 on 2024-12-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_project_proposal_request_report_proposalimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects/<django.db.models.fields.related.ForeignKey>/'),
        ),
        migrations.AlterField(
            model_name='proposalimage',
            name='image',
            field=models.ImageField(upload_to='proposals/<django.db.models.fields.related.ForeignKey>/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(upload_to='reports/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
