# Generated by Django 4.2.7 on 2024-12-07 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_projectimage_image_alter_proposalimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=255)),
                ('sub_agency', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_definition', models.TextField()),
                ('objective', models.TextField()),
                ('justification_area', models.TextField()),
                ('coal_benefit', models.TextField()),
                ('subject_justification', models.TextField()),
                ('work_plan', models.TextField()),
                ('methodology', models.TextField()),
                ('organization', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('capital_expenditure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salaries', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumables', models.DecimalField(decimal_places=2, max_digits=10)),
                ('travel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('workshops', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('co_investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_investigator_projects', to=settings.AUTH_USER_MODEL)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='investigator_list',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='proposalimage',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='report',
            name='project',
        ),
        migrations.RemoveField(
            model_name='request',
            name='project',
        ),
        migrations.DeleteModel(
            name='AuditTrail',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
        migrations.DeleteModel(
            name='ProposalImage',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
