# Generated by Django 4.2.7 on 2024-12-07 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_projectproposal_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Success', 'Success'), ('In Review', 'In Review'), ('Cancelled', 'Cancelled')], default='Processing', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current_progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('progress_status', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(max_length=50)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('funds_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_investigators', models.ManyToManyField(related_name='user_projects', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_projects', to='accounts.projectproposal')),
            ],
        ),
    ]
