# Generated by Django 4.2.7 on 2024-12-11 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_project_budget_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenditureQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(choices=[('A', 'Land & Building'), ('B', 'Capital Equipment'), ('C', 'Manpower'), ('D', 'Consumable'), ('E', 'TA/DA'), ('F', 'Contingencies')], max_length=1)),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuarterlyExpenditureStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=255)),
                ('company_institute_name', models.CharField(max_length=255)),
                ('quarter_ending', models.DateField()),
                ('equipment_name', models.CharField(max_length=255)),
                ('supplier_name', models.CharField(max_length=255)),
                ('number_of_units', models.IntegerField()),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_approved_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('progressive_capital_expenditure', models.DecimalField(decimal_places=2, max_digits=15)),
                ('building_or_land_area', models.TextField(blank=True, null=True)),
                ('associate_finance_officer_name', models.CharField(max_length=255)),
                ('associate_finance_officer_designation', models.CharField(max_length=255)),
                ('associate_finance_officer_signature', models.ImageField(blank=True, null=True, upload_to='signatures/finance_officer/')),
                ('project_leader_name', models.CharField(max_length=255)),
                ('project_leader_designation', models.CharField(max_length=255)),
                ('project_leader_signature', models.ImageField(blank=True, null=True, upload_to='signatures/project_leader/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_expenditures', to='accounts.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCompletionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('project_code', models.CharField(max_length=100)),
                ('date_of_commencement', models.DateField()),
                ('approved_completion_date', models.DateField()),
                ('actual_completion_date', models.DateField()),
                ('objectives', models.TextField()),
                ('work_programme', models.TextField()),
                ('details_of_work_done', models.TextField()),
                ('objectives_fulfilled', models.TextField()),
                ('reasons_for_incomplete_scope', models.TextField(blank=True, null=True)),
                ('need_for_further_study', models.TextField(blank=True, null=True)),
                ('conclusions_and_recommendations', models.TextField()),
                ('scope_of_application', models.TextField()),
                ('associated_persons', models.TextField()),
                ('final_expenditure_statement', models.FileField(upload_to='completion_reports/expenditure_statements/')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_report', to='accounts.project')),
            ],
        ),
        migrations.CreateModel(
            name='IncrementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increment_type', models.CharField(choices=[('Time', 'Time'), ('Cost', 'Cost')], max_length=10)),
                ('increment_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('feedback_message', models.TextField()),
                ('feedback_image', models.ImageField(blank=True, null=True, upload_to='increment_requests/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increment_requests', to='accounts.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_increment_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FundRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_approved_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_fund_received_as_on', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_earned', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expenditure_incurred_till_date', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_fund_available_as_on_date', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fund_provision_in_corresponding_year', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fund_required_for_year_period', models.DecimalField(decimal_places=2, max_digits=15)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_requisitions', to='accounts.project')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_approved_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_fund_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_used_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('interest_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('balance_available', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cost_used_last_year', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cost_used_previous_quarter', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cost_used_till_present_quarter_end', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('overall_expenditure', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('number_of_units', models.IntegerField(default=0)),
                ('unit_values', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_analysis', to='accounts.project')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('reply', models.CharField(max_length=255)),
                ('feedback_image', models.FileField(upload_to='feedback')),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectname', to='accounts.project')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenditureStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_institute_name', models.CharField(max_length=255)),
                ('quarter_ending', models.DateField()),
                ('total_approved_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sanctioned_provision_in_year', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expenditure_incurred_previous_year', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expenditure_up_to_previous_quarter', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expenditure_in_present_quarter', models.DecimalField(decimal_places=2, max_digits=15)),
                ('progressive_expenditure_till_date', models.DecimalField(decimal_places=2, max_digits=15)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditure_statements', to='accounts.project')),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_codes', to='accounts.project')),
            ],
        ),
    ]
