# Generated by Django 4.2.7 on 2024-12-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_expenditurequestion_quarterlyexpenditurestatement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcompletionreport',
            old_name='conclusions_and_recommendations',
            new_name='conclusions',
        ),
        migrations.RenameField(
            model_name='projectcompletionreport',
            old_name='details_of_work_done',
            new_name='expenditure_statement',
        ),
        migrations.RenameField(
            model_name='projectcompletionreport',
            old_name='need_for_further_study',
            new_name='need_for_further_studies',
        ),
        migrations.RenameField(
            model_name='projectcompletionreport',
            old_name='title',
            new_name='project_title',
        ),
        migrations.RenameField(
            model_name='projectcompletionreport',
            old_name='reasons_for_incomplete_scope',
            new_name='reasons_for_not_covering',
        ),
        migrations.RenameField(
            model_name='projectcompletionreport',
            old_name='date_of_commencement',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='projectcompletionreport',
            name='final_expenditure_statement',
        ),
        migrations.RemoveField(
            model_name='projectcompletionreport',
            name='project',
        ),
        migrations.AddField(
            model_name='projectcompletionreport',
            name='work_done',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
