# Generated by Django 4.2.7 on 2024-12-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_conclusions_and_recommendations_projectcompletionreport_conclusions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcompletionreport',
            old_name='actual_completion_date',
            new_name='actualCompletionDate',
        ),
        migrations.RenameField(
            model_name='projectcompletionreport',
            old_name='approved_completion_date',
            new_name='approvedCompletionDate',
        ),
        migrations.RenameField(
            model_name='projectcompletionreport',
            old_name='associated_persons',
            new_name='associatedPersons',
        ),
        migrations.RenameField(
            model_name='projectcompletionreport',
            old_name='expenditure_statement',
            new_name='expenditureStatement',
        ),
        migrations.RenameField(
            model_name='projectcompletionreport',
            old_name='need_for_further_studies',
            new_name='needForFurtherStudies',
        ),
        migrations.RenameField(
            model_name='projectcompletionreport',
            old_name='objectives_fulfilled',
            new_name='objectivesFulfilled',
        ),
        migrations.RenameField(
            model_name='projectcompletionreport',
            old_name='project_code',
            new_name='projectCode',
        ),
        migrations.RenameField(
            model_name='projectcompletionreport',
            old_name='project_title',
            new_name='projectTitle',
        ),
        migrations.RenameField(
            model_name='projectcompletionreport',
            old_name='reasons_for_not_covering',
            new_name='reasonsForNotCovering',
        ),
        migrations.RenameField(
            model_name='projectcompletionreport',
            old_name='scope_of_application',
            new_name='scopeOfApplication',
        ),
        migrations.RenameField(
            model_name='projectcompletionreport',
            old_name='start_date',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='projectcompletionreport',
            old_name='work_done',
            new_name='workDone',
        ),
        migrations.RenameField(
            model_name='projectcompletionreport',
            old_name='work_programme',
            new_name='workProgramme',
        ),
    ]
