# Generated by Django 4.2.7 on 2024-12-11 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_projectrevision_projectid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.CharField(max_length=100, unique=True)),
                ('projectName', models.CharField(max_length=255)),
                ('projectCode', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=255)),
                ('statementPeriod', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('approvedCost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fundReceived', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interestEarned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expenditureIncurred', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fundProvision', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fundRequired', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balanceFund', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.projectfund')),
            ],
        ),
    ]
