# Generated by Django 4.2.7 on 2024-12-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_projectfund_projectid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndorsementForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.IntegerField()),
                ('projectTitle', models.CharField(max_length=255)),
                ('projectLeader', models.CharField(max_length=255)),
                ('infrastructureFacilities', models.BooleanField(default=False)),
                ('transportManpower', models.BooleanField(default=False)),
                ('equipmentProcurement', models.BooleanField(default=False)),
                ('financialResponsibility', models.BooleanField(default=False)),
                ('headOfInstitution', models.CharField(max_length=255)),
                ('seal', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=255)),
            ],
        ),
    ]
