# Generated by Django 4.2.7 on 2024-12-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_endorsementform'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyStatusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=255)),
                ('projectCode', models.CharField(blank=True, max_length=255, null=True)),
                ('progress', models.TextField()),
                ('principalImplementingAgency', models.CharField(max_length=255)),
                ('subImplementingAgency', models.CharField(max_length=255)),
                ('projectCoordinator', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('approvedCompletionDate', models.DateField()),
                ('workDone', models.TextField()),
                ('slippage', models.TextField(blank=True, null=True)),
                ('correctiveActions', models.TextField()),
                ('workNextQuarter', models.TextField()),
                ('barChart', models.FileField(upload_to='bar_charts/')),
                ('formIII', models.FileField(upload_to='forms/')),
                ('formIV', models.FileField(upload_to='forms/')),
            ],
        ),
    ]
