# Generated by Django 4.2.7 on 2024-12-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_quarterlystatusreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCompletionReport2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('projectCode', models.CharField(max_length=255)),
                ('commencementDate', models.DateField()),
                ('approvedCompletionDate', models.DateField()),
                ('actualCompletionDate', models.DateField()),
                ('objectives', models.TextField()),
                ('workProgram', models.TextField()),
                ('workDetails', models.TextField()),
                ('objectivesFulfilled', models.TextField()),
                ('reasonsForSlippage', models.TextField(blank=True, null=True)),
                ('furtherStudiesNeeded', models.TextField()),
                ('conclusionsAndRecommendations', models.TextField()),
                ('scopeOfApplication', models.TextField()),
                ('associatedPersons', models.TextField()),
                ('finalExpenditure', models.TextField(blank=True, null=True)),
                ('formIII', models.FileField(upload_to='forms/')),
                ('formIV', models.FileField(upload_to='forms/')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectCompletionReport',
        ),
    ]
