# Generated by Django 4.2.7 on 2024-12-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_projectextensionreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRevisionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.IntegerField()),
                ('projectName', models.CharField(max_length=255)),
                ('projectCode', models.CharField(max_length=255)),
                ('implementingAgency', models.CharField(max_length=255)),
                ('projectLeader', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('scheduledCompletionDate', models.DateField()),
                ('approvedObjective', models.TextField()),
                ('approvedWorkProgram', models.TextField()),
                ('workDetails', models.TextField()),
                ('revisedCost', models.TextField()),
                ('approvedCost', models.TextField()),
                ('revisedSchedule', models.TextField()),
                ('actualExpenditure', models.FloatField()),
                ('formIII', models.FileField(blank=True, null=True, upload_to='forms/')),
                ('formIV', models.FileField(blank=True, null=True, upload_to='forms/')),
                ('justification', models.TextField()),
            ],
        ),
    ]
