# Generated by Django 4.2.7 on 2024-12-11 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_projectrevisiontwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.IntegerField()),
                ('projectName', models.CharField(max_length=255)),
                ('projectCode', models.CharField(max_length=255)),
                ('principalAgency', models.CharField(max_length=255)),
                ('subAgency', models.CharField(max_length=255)),
                ('justification', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('noOfSets', models.IntegerField()),
                ('makeModel', models.CharField(max_length=255)),
                ('yearOfProcurement', models.CharField(max_length=50)),
                ('procuredProject', models.CharField(max_length=255)),
                ('presentCondition', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipmentDetails', to='accounts.projectequipment')),
            ],
        ),
    ]
