# Generated by Django 4.2.7 on 2024-12-11 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_projectequipment_equipmentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.IntegerField()),
                ('projectName', models.CharField(max_length=255)),
                ('projectCode', models.CharField(max_length=255)),
                ('principalAgency', models.CharField(max_length=255)),
                ('subAgency', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ManpowerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('noOfPersons', models.IntegerField()),
                ('totalMonths', models.IntegerField()),
                ('salaryPerMonth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalSalary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('firstYear', models.DecimalField(decimal_places=2, max_digits=10)),
                ('secondYear', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thirdYear', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpowerDetails', to='accounts.projectmanpower')),
            ],
        ),
    ]
