# Generated by Django 4.2.7 on 2024-12-12 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_timelinetask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assigned_investigators',
            field=models.ManyToManyField(blank=True, related_name='user_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gstRate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('otherTaxRate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=15)),
                ('otherTaxes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remainingAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='accounts.project')),
            ],
        ),
    ]
