# Generated by Django 4.2.7 on 2024-12-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_project_assigned_investigators_fund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='fundAmount',
            new_name='fund_amount',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='gstRate',
            new_name='gst_rate',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='otherTaxRate',
            new_name='other_tax_rate',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='otherTaxes',
            new_name='other_taxes',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='remainingAmount',
            new_name='remaining_amount',
        ),
    ]
