from django.contrib import admin
from . import models
# Register your models here.
admin.site.register(models.User)
admin.site.register(models.ProjectProposal)
# admin.site.register(models.ProposalImage)
admin.site.register(models.Project)
# admin.site.register(models.ProjectImage)
admin.site.register(models.Report)

admin.site.register(models.Feedback)
admin.site.register(models.FundRequisition)
admin.site.register(models.ExpenditureQuestion)
admin.site.register(models.ExpenditureStatement)
admin.site.register(models.QuarterlyExpenditureStatement)
# admin.site.register(models.ProjectCompletionReport)
admin.site.register(models.FinanceAnalysis)
admin.site.register(models.ProjectCompletionReport2)
admin.site.register(models.ProjectRevision)
admin.site.register(models.Item)
admin.site.register(models.ProjectFund)
admin.site.register(models.EndorsementForm)
admin.site.register(models.QuarterlyStatusReport)
# admin.site.register(models.ProjectCompletionReport)
admin.site.register(models.ProjectExtensionReport)
admin.site.register(models.ProjectRevisionTwo)
# admin.site.register(models.EquipmentDetail)
admin.site.register(models.EquipmentDetail)
admin.site.register(models.ProjectEquipment)
admin.site.register(models.ProjectManpower)
admin.site.register(models.ManpowerDetail)
admin.site.register(models.ProjectTravel)
admin.site.register(models.TravelDetail)
admin.site.register(models.TimelineTask)
admin.site.register(models.Fund)